---
# role: ansible-role-updates
# file: molecule/all/molecule.yml

dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: amazon-updates
    image: "jomrr/molecule-amazonlinux:latest"
    command: ~
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: centos7-updates
    image: "jomrr/molecule-centos:7"
    command: ~
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: centos8-updates
    image: "jomrr/molecule-centos:8"
    command: ~
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: debian9-updates
    image: "jomrr/molecule-debian:9"
    command: ~
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: debian10-updates
    image: "jomrr/molecule-debian:10"
    command: ~
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: debian-updates
    image: "jomrr/molecule-debian:latest"
    command: ~
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: fedora-updates
    image: "jomrr/molecule-fedora:latest"
    command: ~
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: oracle7-updates
    image: "jomrr/molecule-oraclelinux:7"
    command: ~
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: oracle8-updates
    image: "jomrr/molecule-oraclelinux:8"
    command: ~
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: oracle-updates
    image: "jomrr/molecule-oraclelinux:latest"
    command: ~
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ubuntu1604-updates
    image: "jomrr/molecule-ubuntu:16.04"
    command: ~
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ubuntu1804-updates
    image: "jomrr/molecule-ubuntu:18.04"
    command: ~
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ubuntu2004-updates
    image: "jomrr/molecule-ubuntu:20.04"
    command: ~
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ubuntu-updates
    image: "jomrr/molecule-ubuntu:latest"
    command: ~
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
provisioner:
  name: ansible
  log: true
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/converge.yml
    verify: ../resources/playbooks/verify.yml
  inventory:
    group_vars:
      all:
        updates_role_enabled: true
verifier:
  name: ansible
