---
# role: jomrr.updates
# file: molecule/kvm/molecule.yml

dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt
    options:
      memory: 2048
      cpus: 2
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: centos7-updates
    box: "centos/7"
  - name: centos8-updates
    box: "centos/8"
  - name: debian9-updates
    box: "debian/stretch64"
  - name: debian10-updates
    box: "debian/buster64"
  - name: debian11-updates
    box: "debian/bullseye64"
  - name: fedora33-updates
    box: "fedora/33-cloud-base"
  - name: oracle7-updates
    box: "generic/oracle7"
  - name: oracle8-updates
    box: "centos/oracle8"
  - name: ubuntu1804-updates
    box: "generic/ubuntu1804"
  - name: ubuntu2004-updates
    box: "generic/ubuntu2004"
provisioner:
  name: ansible
  log: true
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/converge.yml
    verify: ../resources/playbooks/verify.yml
  inventory:
    group_vars:
      all:
        updates_role_enabled: true
verifier:
  name: ansible
