---
# role: ansible-role-updates
# file: molecule/default/molecule.yml

dependency:
  name: galaxy
driver:
  name: podman
lint:
  name: yamllint
  options:
    config-file: molecule/shared/yamllint.yml
platforms:
  - name: updates-default
    image: ${MOLECULE_DIST:-"jam82/oracle-molecule:8"}
    command: ${MOLECULE_DOCKER_CMD:-""}
    pre_build_image: True
    tty: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
provisioner:
  name: ansible
  log: True
  lint:
    name: ansible-lint
  playbooks:
    prepare: ../shared/prepare.yml
    converge: ../shared/playbook.yml
  inventory:
    group_vars:
      all:
        updates_enabled: True
scenario:
  name: podman
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore"
  directory: ../tests
  options:
    v: True
    sudo: True
  lint:
    name: flake8
