---
# role: ansible-role-updates
# file: molecule/tox/molecule.yml

dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: updates-${TOX_ENVNAME:-"default"}
    image: ${MOLECULE_IMG:-"jomrr/molecule-debian:latest"}
    command: ""
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
provisioner:
  name: ansible
  log: true
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/converge.yml
    verify: ../resources/playbooks/verify.yml
  inventory:
    group_vars:
      all:
        updates_role_enabled: true
verifier:
  name: ansible
